<h1>Ajouter un nouveau Produit Details </h1>
<form id="form1" method="post">

	<table>
		<tr>
			<td>Poids : </td>
			<td><input type="text" id="poids" name="poids"/>(g)
			<span id="erreur">
			<?php
			echo $this->viewData['prod_details']->ValidationMessage("poids");
			?></span>
			</td>
		</tr>
		<tr>
			<td>Prix : </td>
			<td><input type="text" id="prix" name="prix"/>(DT)
			<span id="erreur">
			<?php
			echo $this->viewData['prod_details']->ValidationMessage("prix");
			?></span>
			</td>
		</tr>
		<tr>
			<td>Quantité : </td>
			<td><input type="text" id="quantite" name="quantite"/>
			<span id="erreur">
			<?php
			echo $this->viewData['prod_details']->ValidationMessage("quantite");
			?></span>
			</td>
		</tr>
	<!--			<tr><td colspan="2"><input type="submit" value="Ajouter" /></td></tr>  -->
			</table>
			<input type="submit" value="Ajouter"  />

		</form>
<a href="?controler=Prod_details&action=index&id=<?php echo $this->viewData['id_prod']?>">Retour</a>
