<h1>Supprimer un Specialite</h1>
<form id="form1" method="post"><table>	<tr>
		<td>ID : </td>
		<td><input readonly type="text" id="spe_id" name="spe_id" 
			value="<?php echo $this->viewData['specialite']->getspe_id();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['specialite']->ValidationMessage("spe_id");
			?></span>
		</td>
	</tr>
	<tr>
		<td>Libele : </td>
		<td><input readonly type="text" id="spe_name" name="spe_name" 
			value="<?php echo $this->viewData['specialite']->getspe_name();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['specialite']->ValidationMessage("spe_name");
			?></span>
		</td>
	</tr>
				<tr><td colspan="2"><input type="submit" value="Supprimer" /></td></tr>
			</table>
		</form>
	<a href="?controler=Specialite">Retour</a>
