<h1>Supprimer un Li_med</h1>
<form id="form1" method="post"><table>	<tr>
		<td>ID : </td>
		<td><input readonly type="text" id="li_id" name="li_id" 
			value="<?php echo $this->viewData['li_med']->getli_id();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['li_med']->ValidationMessage("li_id");
			?></span>
		</td>
	</tr>
			<tr>
				<td>Zone : </td>
				<td>
					<select id="zone_id" name="zone_id">
					<?php 
 					foreach($this->viewData["listZone"] as $cat){ 
							if($cat["zone_id"] == $this->viewData['li_med']->getzone_id()){
 							echo '<option value="'.$cat["zone_id"]. '" selected>'.$cat['zone_name'].'</option>'; 
							}else{
 							echo '<option value="'.$cat["zone_id"]. '">'.$cat['zone_name'].'</option>'; }}
					?> </select></td></tr> 
	<tr>
		<td>Medecin : </td>
		<td><input readonly type="text" id="med_id" name="med_id" 
			value="<?php echo $this->viewData['li_med']->getmed_id();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['li_med']->ValidationMessage("med_id");
			?></span>
		</td>
	</tr>
	<tr>
		<td>Tel : </td>
		<td><input readonly type="text" id="med_phone" name="med_phone" 
			value="<?php echo $this->viewData['li_med']->getmed_phone();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['li_med']->ValidationMessage("med_phone");
			?></span>
		</td>
	</tr>
	<tr>
		<td>Adresse : </td>
		<td><input readonly type="text" id="med_address" name="med_address" 
			value="<?php echo $this->viewData['li_med']->getmed_address();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['li_med']->ValidationMessage("med_address");
			?></span>
		</td>
	</tr>
	<tr>
		<td>City : </td>
		<td><input readonly type="text" id="med_city" name="med_city" 
			value="<?php echo $this->viewData['li_med']->getmed_city();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['li_med']->ValidationMessage("med_city");
			?></span>
		</td>
	</tr>
	<tr>
		<td>Code postale : </td>
		<td><input readonly type="text" id="med_zip" name="med_zip" 
			value="<?php echo $this->viewData['li_med']->getmed_zip();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['li_med']->ValidationMessage("med_zip");
			?></span>
		</td>
	</tr>
	<tr>
		<td>Municipalité : </td>
		<td><input readonly type="text" id="mun_id" name="mun_id" 
			value="<?php echo $this->viewData['li_med']->getmun_id();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['li_med']->ValidationMessage("mun_id");
			?></span>
		</td>
	</tr>
				<tr><td colspan="2"><input type="submit" value="Supprimer" /></td></tr>
			</table>
		</form>
	<a href="?controler=Li_med">Retour</a>
