<h1>Supprimer un Zone</h1>
<form id="form1" method="post"><table>	<tr>
		<td>ID : </td>
		<td><input readonly type="text" id="zone_id" name="zone_id" 
			value="<?php echo $this->viewData['zone']->getzone_id();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['zone']->ValidationMessage("zone_id");
			?></span>
		</td>
	</tr>
	<tr>
		<td>Libele : </td>
		<td><input readonly type="text" id="zone_name" name="zone_name" 
			value="<?php echo $this->viewData['zone']->getzone_name();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['zone']->ValidationMessage("zone_name");
			?></span>
		</td>
	</tr>
	<tr>
		<td>Parent zone : </td>
		<td><input readonly type="text" id="zone_pid" name="zone_pid" 
			value="<?php echo $this->viewData['zone']->getzone_pid();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['zone']->ValidationMessage("zone_pid");
			?></span>
		</td>
	</tr>
	<tr>
		<td>Gouvernorat : </td>
		<td><input readonly type="text" id="gov_id" name="gov_id" 
			value="<?php echo $this->viewData['zone']->getgov_id();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['zone']->ValidationMessage("gov_id");
			?></span>
		</td>
	</tr>
				<tr><td colspan="2"><input type="submit" value="Supprimer" /></td></tr>
			</table>
		</form>
	<a href="?controler=Zone">Retour</a>
