<?php
	function getScale($list)
	{
		$max=-1;
		foreach ($list as $key => $value) 
		{
			if($value['prix']>$max)
			{
				$max=$value['prix'];
			}
		}
		return $max;
	}
	$tc=$this->viewData['listCategorie'];
	echo '<h3 class="sidebar__title"><span class="light">Cat.</span> '.$tc[0]['libelle'].'</h3><hr class="shop__divider">
        <div class="shop-filter">
          <h5 class="sidebar__subtitle">Catégories</h5>
          <ul class="nav  nav--filter">';
          $s="";
          if(isset($_GET['search']))
          {
          	$s='&search='.$_GET['search'];
          }
          foreach ($tc as $i => $v) 
          {
          		echo '<li><a href="?category='.$v['categorie_id'].$s.'">'.$v['libelle'].'</a></li>';
          }
          echo '<li><a href="produits-list.php">Afficher tous les produits</a></li>
          		</ul>
		          <hr class="divider">
		          <h5 class="sidebar__subtitle">Prix</h5>
		          <div class="shop__filter__slider">
		            <div class="js--jqueryui-price-filter"></div>
		          </div>
		        </div>
		      </aside>
		    </div>
		    <div class="col-xs-12  col-sm-9">
		      <div class="grid">
		        <ul class="pagination  shop__amount-filter">
		          <li> <a class="shop__amount-filter__link  hidden-xs" href="produits-grille.php"><span class="glyphicon glyphicon-th"></span></a> </li>
		          <li> <a class="shop__amount-filter__link  hidden-xs" href="produits-list.php"><span class="glyphicon glyphicon-th-list"></span></a> </li>
		        </ul>
		        <div class="shop__sort-filter">
		          <select name="select" class="js--isotope-sorting  btn  btn-shop">
		            <option value=\'{"sortBy":"price", "sortAscending":"true"}\'>Par Prix (croissant) &uarr;</option>
		            <option value=\'{"sortBy":"price", "sortAscending":"false"}\'>Par Prix (décroissant) &darr;</option>
		            <option value=\'{"sortBy":"name", "sortAscending":"true"}\'>Par Nom (croissant) &uarr;</option>
		            <option value=\'{"sortBy":"name", "sortAscending":"false"}\'>Par Nom (décroissant) &darr;</option>
		            <option value=\'{"sortBy":"rating", "sortAscending":"true"}\'>Par note (croissant) &uarr;</option>
		            <option value=\'{"sortBy":"rating", "sortAscending":"false"}\'>Par note (décroissant) &darr;</option>
		          </select>
		        </div>
		        <hr class="shop__divider">
		        <div class="row  js--isotope-container">'; 

		        $x=$this->viewData['listdetailsproduits'];
				$y=$this->viewData['listCategorie'];
				$z=$this->viewData['listPhoto'];
				function getPriceScale($id,$x)
				{
					for ($i=0; $i < count($x); $i++) 
					{ 
						if($x[$i]['id_prod']==$id)
						{
							return $x[$i]['prix']*20/getScale($x);
						}
					}
					return 0;
				}
				function getCategoryName($id,$x)
				{
					for ($i=0; $i < count($x); $i++) 
					{ 
						if($x[$i]['categorie_id']==$id)
						{
							return $x[$i]['libelle'];
						}
					}
					return "catégorie non identifiée.";
				}
				function getFirstProductPhoto($id,$x)
				{
					for ($i=0; $i < count($x); $i++) 
					{ 
						if($x[$i]['id_prod']==$id)
						{
							return $x[$i]['photo'];
						}
					}
					return "d.jpg";
				}
				function isParentedBy($f,$p,$x)
				{
					foreach ($x as $key => $value) 
					{
						if($value['categorie_id']==$f && $value['id_parent']==$p)
						{
							return true;
						}
					}
					return false;
				}
				function getProductsPerCategory($id,$p,$x)
				{
					$t=array();
					$j=0;
					foreach ($p as $key => $value) 
					{
						if($value['categorie_id']==$id || isParentedBy($value['categorie_id'],$id,$x))
						{
							$t[$j]=$value;
							$j++;
						}
					}
					return $t;
				}
		        $tab=$this->viewData['listProduit'];
		        if(isset($_GET['search']))
		        {
		        	$ts=array();
		        	foreach ($tab as $key => $value) 
		        	{
	        			if ((strstr($value['nom'],$_GET['search'])!==false)) 
						{
	        				$ts[]=$value;	
	        			}
		        	}
		        	$tab=$ts;
		        }
		        if(isset($_GET['category']))
		        {
		        	$tab=getProductsPerCategory($_GET['category'],$tab,$this->viewData['listCategorie']);
		        }
		        $page=$_GET['page'];
		        for ($i=($page-1)*2;$i<$page*2 && $i <count($tab) ; $i++) 
		        { 
		        	
		        		$id=$tab[$i]['produit_id'];
		        		$name=$tab[$i]['nom'];
						$c_id=getCategoryName($tab[$i]['categorie_id'],$y);
						$photo=getFirstProductPhoto($id,$z);
		        		$stock='<span class="out-of-stock">&bull;</span> <span class="in-stock--text">Stock épuisé</span>';
						if($tab[$i]['quantite_stock']>0)
							$stock='<span class="in-stock">&bull;</span> <span class="in-stock--text">En stock</span>';
			          	echo '<div class="col-xs-6 col-sm-3  js--isotope-target  js--cat-1" data-price="'.getPriceScale($id,$x).'" data-rating="5">
					            <div class="products__single">
					              <div class="products__image  push-down-15"> <a href="produit-details.php?id='.$id.'"> <img alt="#" class="product__image" width="360" height="458" src="images/produits/'.$photo.'"> </a>
					                <div class="product-overlay"><a class="product-overlay__more" href="produit-details.php?id='.$id.'"> <span class="glyphicon glyphicon-search"></span> </a> <a class="product-overlay__cart" href="#"> +<span class="glyphicon glyphicon-shopping-cart"></span> </a>
					                  <div class="product-overlay__stock"> '.$stock.' </div>
					                </div>
					              </div>
					            </div>
					          </div>
					          <div class="col-sm-9  js--isotope-target  js--cat-1" data-price="'.getPriceScale($id,$x).'" data-rating="5"> <br>
					            <div class="products__title">
					              <h5 class="products__title"><a class="products__link  js--isotope-title" href="produit-details.php?id='.$id.'">'.$name.'</a></h5>
					            </div>
					            <div class="products__price"> '.(getPriceScale($id,$x)*getScale($x)/20).'$ </div>
					            <p> '.$tab[$i]['description'].' </p>
					          </div>';
			        
		        	
		        }
		        
		        $count=(ceil(count($tab)/2));
			    echo '
			        </div>
			        <div class="clearfix  hidden-xs"></div>
			      </div>
			      <hr class="shop__divider">
			      <div class="shop__pagination">
			        <ul class="pagination">';
			        	$cat='';
			        if (isset($_GET['category'])) 
			        {
			        	$cat='&category='.$_GET['category'];
			        }
			        if(isset($_GET['search']))
			        {
			        	$cat.='&search='.$_GET['search'];
			        }
			        if ($page!=1) 
			        {
			        	echo '<li><a class="pagination--nav" href="?page='.($page-1).$cat.'"><span class="glyphicon glyphicon-chevron-left"></span></a></li>';
			        }
			        for ($i=1; $i <= $count; $i++) 
			        { 
			        	if($i==$page)
			        		echo '<li><a class="active" href="javascript:void(0);">'.$page.'</a></li>';
			        	else
			        		echo '<li><a href="?page='.$i.$cat.'">'.$i.'</a></li>';

			        }
			        if ($page!=$count) 
			        {
			        	echo '<li><a class="pagination--nav" href="?page='.($page+1).$cat.'"><span class="glyphicon glyphicon-chevron-right"></span></a></li>';
			        }
			          
			    echo '
			        </ul>
			      </div>
			    </div>
			  </div>
			</div>
			<div class="search-mode__overlay"></div>
    		<script data-main="scripts/main" src="bower_components/requirejs/require.js"></script>
			
			';  

			//javascript here -- dont forget to do it -- price scale filter

?>

