<h1>Ajouter un nouveau Fonction</h1><form id="form1" method="post">		<table>	<tr>
		<td>Libele : </td>
		<td><input type="text" id="fonc_name" name="fonc_name" 
			value="<?php echo $this->viewData['fonction']->getfonc_name();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['fonction']->ValidationMessage("fonc_name");
			?></span>
		</td>
	</tr>
				<tr><td colspan="2"><input type="submit" value="Ajouter" /></td></tr>
			</table>
		</form>
	<a href="?controler=Fonction">Retour</a>
