<h1>Modifier un Fonction</h1>
<form id="form1" method="post"><table>	<tr>
		<td>ID : </td>
		<td><input readonly type="text" id="fonc_id" name="fonc_id" 
			value="<?php echo $this->viewData['fonction']->getfonc_id();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['fonction']->ValidationMessage("fonc_id");
			?></span>
		</td>
	</tr>
	<tr>
		<td>Libele : </td>
		<td><input   type="text" id="fonc_name" name="fonc_name" 
			value="<?php echo $this->viewData['fonction']->getfonc_name();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['fonction']->ValidationMessage("fonc_name");
			?></span>
		</td>
	</tr>
			<!--	<tr><td colspan="2"></td></tr>-->
			</table><input type="submit" value="Modifier" />
		</form>
	<a href="?controler=Fonction">Retour</a>
