<h1>Ajouter un nouveau produit</h1>
<form id="form1" method="post">
	<?php

	foreach ( $this->viewData['listLangues'] as $lang) :
		?>
		<FIELDSET><LEGEND align=top><?php echo $lang["libelle"]?>  </LEGEND>
Designation :
			<input type="text" name="lib<?php echo $lang["code"]?>" id="lib<?php echo $lang["code"]?>"/>
		   		<span id="erreur"><?php echo $this->viewData['produit']->ValidationMessage("nom");?></span>
Description :
			<textarea type="text" id="desc<?php echo $lang["code"]?>" name="desc<?php echo $lang["code"]?>" COLS=40 ROWS=6 ></TEXTAREA>
				<span id="erreur"><?php echo $this->viewData['produit']->ValidationMessage("description"); ?></span>
		</FIELDSET>

		<?php


	endforeach;

	?>

<table>
		<tr>
			<td>Promotion : </td>
			<td><input type="text" id="promotion" name="promotion"
					   value="<?php echo $this->viewData['produit']->getPromotion();?>"/>(%)
			<span id="erreur">
			<?php
			echo $this->viewData['produit']->ValidationMessage("promotion");
			?></span>
			</td>
		</tr>
		<tr>
			<td>Categorie : </td>
			<td>
				<select id="categorie" name="categorie">
					<?php 
						foreach($this->viewData['listCategorie'] as $cat)
						{	$list = explode("#bis#",$cat['libelle']);
							echo '<option value="'.$cat['categorie_id'].'">
							'.$list[1].'</option>';}

					?>
				</select>
			</td>
		</tr>

	<tr>
		<td>Photo 1 : </td>
		<td><input type="file" id="photo1" name="photo1"</td>
	</tr>
	<tr>
		<td>Photo 2 : </td>
		<td><input type="file" id="photo2" name="photo2"</td>
	</tr>
	<tr>
		<td>Photo 3 : </td>
		<td><input type="file" id="photo3" name="photo3"</td>
	</tr>
	<tr>
		<td>Photo 4 : </td>
		<td><input type="file" id="photo4" name="photo4"</td>
	</tr>
	<tr>
		<td>Photo 5 : </td>
		<td><input type="file" id="photo5" name="photo5"</td>
	</tr>
	<?php
	$_POST['en_new'] = 0 ;
	$_POST['en_top'] = 0 ;
	$_POST['en_vedette'] = 0 ;?>
	<tr><td></td><INPUT type="checkbox" id="en_new" name="en_new" value="1"> Nouveauté</td>
		<td></td><INPUT type="checkbox" id="en_top" name="en_top" value="1"> Top</td>
		<td></td><INPUT type="checkbox" id="en_vedette" name="en_vedette" value="1"> Vedette</td></tr>


		<tr><td colspan='2'><input type="submit" value="Continue" /></td></tr>
	</table>
</form>

