<h1>Modifier un Categorie</h1>
<form id="form1" method="post"><table>
		<?php
		$list1 = array();
		$list1= $this->viewData['listName'];
		$i = 1;
		foreach ( $this->viewData['listLangues'] as $lang) :
			?>
			<FIELDSET><LEGEND align=top><?php echo $lang["libelle"]?>  </LEGEND>
				Libele :
				<input type="text" name="cat<?php echo $lang["code"]?>" id="cat<?php echo $lang["code"]?>" value = "<?php echo $list1[$i]?>" />
				<span id="erreur"><?php echo $this->viewData['categorie']->ValidationMessage("libelle");?></span>
			</FIELDSET>

			<?php
			$i++;

		endforeach;

		?>
		<tr>
		<td><input readonly type="hidden" id="categorie_id" name="categorie_id"
			value="<?php echo $this->viewData['categorie']->getCategorieId();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['categorie']->ValidationMessage("categorie_id");
			?></span>
		</td>
		</tr>
		<tr>
			<td>Categorie Parent : </td>
			<td>
				<select id="id_parent" name="id_parent">

					<?php
					echo '<option value="0">----</option>';
					foreach($this->viewData['listCategorie'] as $cat)
						if($this->viewData['categorie']->getCategorieId() != $cat['categorie_id'])
							{
								$list = explode("#bis#",$cat['libelle']);
								echo '<option value="'.$cat['categorie_id'].'">
							'.$list[1].'</option>';}

					?>
				</select>

			</td>
		</tr>
				<tr><td colspan="2"><input type="submit" value="Modifier" /></td></tr>
			</table>
		</form>
	<a href="?controler=Categorie&page=1">Retour</a>
<?php echo $this->viewData['erreur']; ?>
