<h1>Modifier un Admin</h1>
<form id="form1" method="post"><table>

		<tr>
		<td><input readonly type="hidden" id="admin_id" name="admin_id"
			value="<?php echo $this->viewData['admin']->getAdminId();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['admin']->ValidationMessage("admin_id");
			?></span>
		</td>
		</tr>
		<tr>
			<td> Ancien Mot de passe : </td>
			<td><input type="password" id="password_old" name="password_old"/>
			<span id="erreur">
			<?php
			echo $this->viewData['admin']->ValidationMessage("password_old");
			?></span>
			</td>
		</tr>
		<tr>
			<td>Nouveau Mot de passe : </td>
			<td><input type="password" id="password" name="password"/>
			<span id="erreur">
			<?php
			echo $this->viewData['admin']->ValidationMessage("password");
			?></span>
			</td>
		</tr>
				<tr><td colspan="2"><input type="submit" value="Modifier" /></td></tr>
			</table>
		</form>
	<a href="?controler=Admin&page=1">Retour</a>
<?php echo $this->viewData['erreur']; ?>
