<h1>Ajouter un nouveau Gouvernorat</h1><form id="form1" method="post">		<table>	<tr>
		<td>Libele : </td>
		<td><input type="text" id="gov_name" name="gov_name" 
			value="<?php echo $this->viewData['gouvernorat']->getgov_name();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['gouvernorat']->ValidationMessage("gov_name");
			?></span>
		</td>
	</tr>
			<tr>
				<td>Gouvernorat : </td>
				<td>
					<select id="count_id" name="count_id">
					<?php 
 					foreach($this->viewData["listCountry"] as $cat){ 
							if($cat["count_id"] == $this->viewData['gouvernorat']->getcount_id()){
 							echo '<option value="'.$cat["count_id"]. '" selected>'.$cat['count_name'].'</option>'; 
							}else{
 							echo '<option value="'.$cat["count_id"]. '">'.$cat['count_name'].'</option>'; }}
					?> </select></td></tr> 
				<tr><td colspan="2"><input type="submit" value="Ajouter" /></td></tr>
			</table>
		</form>
	<a href="?controler=Gouvernorat">Retour</a>
