<h1>Listes de Gouvernorat</h1>
<table>
	<tr>
		<th>ID<th>
		<th>Libele<th>
		<th>Gouvernorat<th>
		<th>Suppression</th>
		<th>Modification</th>
	</tr>
	<?php
	//On récupére la liste a partir de viewData
	foreach($this->viewData["listGouvernorat"] as $gouvernorat):
		echo '<tr>	<td>'.$gouvernorat["gov_id"].'<td>
	<td>'.$gouvernorat["gov_name"].'<td>
	<td>'.$gouvernorat["count_id"].'<td>
		<td><a href="?controler=Gouvernorat&action=modifier&id='.$gouvernorat['gov_id'].'">Modifier</a></td>
		<td><a href="?controler=Gouvernorat&action=supprimer&id='.$gouvernorat['gov_id'].'">Supprimer</a></td>
</tr>';
	endforeach;
	?>
</table>
<a href="?controler=Gouvernorat&action=ajouter">Ajouter un nouveau produit</a>