<h1>Supprimer un Lmed</h1>
<form id="form1" method="post"><table>
<tr><td>li_id: </td>
<td><input type="text" id="li_id" name="li_id" readonly="true" 
value="<?php echo $this->viewData["Lmed"]->getli_id();?>"/></td></tr><tr><td>zone_id</td><td><select id="zone_id" name="zone_id"><?php 
 foreach($this->viewData["listZone"] as $cat){ if($cat["zone_id"] == $this->viewData["Lmed"]->getzone_id()){ echo '<option value="'.$cat["zone_id"]. '" selected>'.$cat['zone_name'].'</option>'; }else{ echo '<option value="'.$cat["zone_id"]. '">'.$cat['zone_name'].'</option>'; }}?> </select></td></tr> <tr><td>med_id</td><td><select id="med_id" name="med_id"><?php 
 foreach($this->viewData["listMedecins"] as $cat){ if($cat["med_id"] == $this->viewData["Lmed"]->getmed_id()){ echo '<option value="'.$cat["med_id"]. '" selected>'.$cat['med_first_name'].'</option>'; }else{ echo '<option value="'.$cat["med_id"]. '">'.$cat['med_first_name'].'</option>'; }}?> </select></td></tr> <tr><td>count_id</td><td><select id="count_id" name="count_id"><?php 
 foreach($this->viewData["listCountry"] as $cat){ if($cat["count_id"] == $this->viewData["Lmed"]->getcount_id()){ echo '<option value="'.$cat["count_id"]. '" selected>'.$cat['count_name'].'</option>'; }else{ echo '<option value="'.$cat["count_id"]. '">'.$cat['count_name'].'</option>'; }}?> </select></td></tr> 
	<tr>
		<td>med_phone : </td>
		<td>
			<input type="text" id="med_phone" name="med_phone"
			value="<?php echo $this->viewData["Lmed"]->getmed_phone();?>"/>
			<span id="erreur">
			<?php 
			echo $this->viewData["Lmed"]->ValidationMessage("med_phone");
			?>
		</span>
	</td></tr>
	<tr>
		<td>med_address : </td>
		<td>
			<input type="text" id="med_address" name="med_address"
			value="<?php echo $this->viewData["Lmed"]->getmed_address();?>"/>
			<span id="erreur">
			<?php 
			echo $this->viewData["Lmed"]->ValidationMessage("med_address");
			?>
		</span>
	</td></tr>
	<tr>
		<td>med_city : </td>
		<td>
			<input type="text" id="med_city" name="med_city"
			value="<?php echo $this->viewData["Lmed"]->getmed_city();?>"/>
			<span id="erreur">
			<?php 
			echo $this->viewData["Lmed"]->ValidationMessage("med_city");
			?>
		</span>
	</td></tr>
	<tr>
		<td>med_zip : </td>
		<td>
			<input type="text" id="med_zip" name="med_zip"
			value="<?php echo $this->viewData["Lmed"]->getmed_zip();?>"/>
			<span id="erreur">
			<?php 
			echo $this->viewData["Lmed"]->ValidationMessage("med_zip");
			?>
		</span>
	</td></tr>
 <tr><td colspan="2"><input type="submit" value="Supprimer" /></td></tr>
 </table></form>