<h1>Ajouter un nouveau Country</h1><form id="form1" method="post">		<table>	<tr>
		<td>Libele : </td>
		<td><input type="text" id="count_name" name="count_name" 
			value="<?php echo $this->viewData['country']->getcount_name();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['country']->ValidationMessage("count_name");
			?></span>
		</td>
	</tr>
				<tr><td colspan="2"><input type="submit" value="Ajouter" /></td></tr>
			</table>
		</form>
	<a href="?controler=Country">Retour</a>
