<h1>Supprimer un Country</h1>
<form id="form1" method="post"><table>	<tr>
		<td>ID : </td>
		<td><input readonly type="text" id="count_id" name="count_id" 
			value="<?php echo $this->viewData['country']->getcount_id();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['country']->ValidationMessage("count_id");
			?></span>
		</td>
	</tr>
	<tr>
		<td>Libele : </td>
		<td><input readonly type="text" id="count_name" name="count_name" 
			value="<?php echo $this->viewData['country']->getcount_name();?>"/>
			<span id="erreur"><?php 
			echo $this->viewData['country']->ValidationMessage("count_name");
			?></span>
		</td>
	</tr>
				<tr><td colspan="2"><input type="submit" value="Supprimer" /></td></tr>
			</table>
		</form>
	<a href="?controler=Country">Retour</a>
