<h1>Ajouter un nouveau Lplanings</h1>
<?php
echo '<pre>';print_r($this->viewData['listPlaning'] );
echo '<pre>';print_r($_COOKIE );
?>
<form id="form1" method="post"><table><tr><td>planing_name</td><td><select id="planing_name" name="planing_name"><?php  
foreach($this->viewData["listPlaning"] as $cat){ 
  if ($_COOKIE["ID_UTILISATEUR"] == $cat["empl_id"] && $_COOKIE["type"]==2 )
     {if($cat["planing_id"] == $this->viewData["Lplanings"]->getplaning_id())
          { echo '<option value="'.$cat["planing_id"]. '" selected>'.$cat['name'].'</option>'; }
          else { echo '<option value="'.$cat["planing_id"]. '">'.$cat['name'].'</option>'; }}


  else {
	 if($cat["planing_id"] == $this->viewData["Lplanings"]->getplaning_id())
          { echo '<option value="'.$cat["planing_id"]. '" selected>'.$cat['name'].'</option>'; }
          else { echo '<option value="'.$cat["planing_id"]. '">'.$cat['name'].'</option>'; }}

}?> </select></td></tr> <tr><td>pro_id</td><td><select id="pro_id" name="pro_id"><?php 
 foreach($this->viewData["listProduits"] as $cat){ if($cat["pro_id"] == $this->viewData["Lplanings"]->getpro_id()){ echo '<option value="'.$cat["pro_id"]. '" selected>'.$cat['pro_name'].'</option>'; }else{ echo '<option value="'.$cat["pro_id"]. '">'.$cat['pro_name'].'</option>'; }}  ?> </select></td></tr> 
 <tr>
		<td>observation : </td>
		<td>
			<input type="text" id="observation" name="observation"
			value="<?php echo $this->viewData["Lplanings"]->getobservation();?>"/>
			<span id="erreur">
			<?php 
			echo $this->viewData["Lplanings"]->ValidationMessage("observation");
			?>
		</span>
	</td></tr>
	<tr>
		<td>etat : </td>
		<td>
			<input type="text" id="etat" name="etat"
			value="<?php echo $this->viewData["Lplanings"]->getetat();?>"/>
			<span id="erreur">
			<?php 
			echo $this->viewData["Lplanings"]->ValidationMessage("etat");
			?>
		</span>
	</td></tr>
	<tr>
		<td>date : </td>
		<td>
			<input type="text" id="date" name="date"
			value="<?php echo $this->viewData["Lplanings"]->getdate();?>"/>
			<span id="erreur">
			<?php 
			echo $this->viewData["Lplanings"]->ValidationMessage("date");
			?>
		</span>
	</td></tr>
 <tr><td colspan="2"><input type="submit" value="Ajouter" /></td></tr>
 </table></form>